--- 
- name: Update cache
  apt:
    update_cache: yes
  become: true

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - make 
    - build-essential 
    - libssl-dev 
    - zlib1g-dev 
    - libbz2-dev 
    - libreadline-dev 
    - libsqlite3-dev 
    - wget 
    - curl 
    - llvm 
    - libncurses5-dev 
    - libncursesw5-dev 
    - xz-utils 
    - tk-dev 
    - tar
  become: true
