---
- name: Copy Python3.10.tgz file 
  copy:
    src: Python-3.10.9.tgz
    dest: /tmp/Python-3.10.9.tgz

- name: Extract Python3.10
  unarchive:
    src: /tmp/Python-3.10.9.tgz
    dest: /tmp
    remote_src: yes
  become: true
 
- name: Set owner and group
  file:
    path: /tmp/Python-3.10.9
    owner: root
    group: root
    recurse: yes
    state: directory
    follow: yes
  become: true

- name: Set Permissions 
  file:
    path: /tmp/Python-3.10.9
    mode: 777
    recurse: yes
    follow: yes
  become: true

- name: Configure and Compile Python3.10
  shell: |
    cd /tmp/Python-3.10.9
    ./configure --enable-optimizations --with-ensurepip=install
    make -j 8
    make altinstall
  become: true 
